development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://zykfftjowduesl:c79b66cb7438f2284342569aadcf1e29fc8c06f85aa2756c325b4417912be242@ec2-23-21-166-148.compute-1.amazonaws.com:5432/dafs309eu00qvb
  channel_prefix: first_app_production
